#! /usr/bin/env python3
import colorama
from colorama import init, Fore
import pyfiglet

import sys
import socket
from datetime import datetime


GREEN = Fore.GREEN
RESET = Fore.RESET
banner = pyfiglet.figlet_format('Port Scanner V  1')
print(banner)

#This was manually typed and will be improved in the next version
top_ports = {
    21: "ftp",
    22: "ssh",
    23: "telnet",
    25: "smtp",
    53: "domain",
    80: "http",
    110: "pop3",
    139: "netbios-ssn",
    143: "imap",
    443: "https",
}

if len(sys.argv) == 2:
    target = socket.gethostbyname(sys.argv[1])
else:
    print("Invalid Number of Arguments")

print('#' * 50)
print("Scanning Target: " + target)
print("Scanning started at: ", datetime.now())
print('#' * 50)

try:

    for port in top_ports:

        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        socket.setdefaulttimeout(1)

        # get the result of the error
        result = s.connect_ex((target, port))

        if result == 0:
            print(f"Port {GREEN}{port}{RESET} is open")
        
        s.close()

except KeyboardInterrupt:
    print("\n Exiting Program !!!")
    sys.exit()

except socket.gaierror:
    print("\n Hostname could not be resolved")
    sys.exit()

except socket.error:
    print(" Server not responding !!!!")
    sys.exit()

